version: '3.8'

services: 
    
    localstack:
        image: localstack/localstack:latest
        ports: 
            - '4566:4566'
        environment: 
            - SERVICES=lambda,s3
            - DEFAULT_REGION=us-east-1
            - EDGE_PORT=4566
    
    terraform:
        image: docker pull hashicorp/terraform:1.0.0
        volumes: 
            - .:/infra
        working_dir: /infra
